// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package generator

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockGenerator creates a new instance of MockGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerator[T any, Options any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerator[T, Options] {
	mockGen := &MockGenerator[T, Options]{}
	mockGen.Mock.Test(t)

	t.Cleanup(func() { mockGen.AssertExpectations(t) })

	return mockGen
}

// MockGenerator is an autogenerated mock type for the Generator type
type MockGenerator[T any, Options any] struct {
	mock.Mock
}

type MockGenerator_Expecter[T any, Options any] struct {
	mock *mock.Mock
}

func (_m *MockGenerator[T, Options]) EXPECT() *MockGenerator_Expecter[T, Options] {
	return &MockGenerator_Expecter[T, Options]{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockGenerator
func (_mock *MockGenerator[T, Options]) Generate(model T, opts Options) (string, error) {
	ret := _mock.Called(model, opts)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(T, Options) (string, error)); ok {
		return returnFunc(model, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(T, Options) string); ok {
		r0 = returnFunc(model, opts)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(T, Options) error); ok {
		r1 = returnFunc(model, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockGenerator_Generate_Call[T any, Options any] struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - model T
//   - opts Options
func (_e *MockGenerator_Expecter[T, Options]) Generate(model interface{}, opts interface{}) *MockGenerator_Generate_Call[T, Options] {
	return &MockGenerator_Generate_Call[T, Options]{Call: _e.mock.On("Generate", model, opts)}
}

func (_c *MockGenerator_Generate_Call[T, Options]) Run(run func(model T, opts Options)) *MockGenerator_Generate_Call[T, Options] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 T
		if args[0] != nil {
			arg0 = args[0].(T)
		}
		var arg1 Options
		if args[1] != nil {
			arg1 = args[1].(Options)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerator_Generate_Call[T, Options]) Return(s string, err error) *MockGenerator_Generate_Call[T, Options] {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGenerator_Generate_Call[T, Options]) RunAndReturn(run func(model T, opts Options) (string, error)) *MockGenerator_Generate_Call[T, Options] {
	_c.Call.Return(run)
	return _c
}
