version: "2"
linters:
  default: all
  settings:
    depguard:
      rules:
        main:
          files:
            - "$all"
            - "!$test"
          list-mode: strict
          allow:
            - $gostd
            - github.com/devantler-tech/ksail-go
            - github.com/k3d-io/k3d
            - github.com/spf13/cobra
            - sigs.k8s.io
    revive:
      enable-all-rules: true
