version: "2"
linters:
  default: all
  settings:
    depguard:
      rules:
        main:
          files:
            - "$all"
            - "!$test"
          list-mode: strict
          allow:
            - $gostd
            - github.com/devantler-tech/ksail-go
            - github.com/docker/docker
            - github.com/fatih/color
            - github.com/k3d-io/k3d
            - github.com/mittwald/go-helm-client
            - github.com/spf13/cobra
            - github.com/stretchr/testify
            - sigs.k8s.io
            - k8s.io
    exhaustruct:
      exclude:
        - '.+/cobra\.Command$'
        - '.+/types\.Cluster$'
        - '.+/v1alpha1\.Cluster$'
        - '.+/v1alpha1\.Spec$'
        - '.+/v1alpha4\.Cluster$'
        - '.+/v1alpha5\.ClusterConfig$'
        - '.+/v1alpha5\.SimpleConfig$'
        - '.+\.ObjectMeta$'
        - '.+\v1alpha4\.Node$'

  exclusions:
    rules:
      - path: "cmd/.+"
        linters:
          - forbidigo
