version: "2"
linters:
  default: all
  enable:
    - wsl_v5
  disable:
    - wsl
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    depguard:
      rules:
        main:
          files:
            - "$all"
            - "!$test"
          list-mode: strict
          allow:
            - $gostd
            - github.com/devantler-tech/ksail-go
            - github.com/docker/docker
            - github.com/fatih/color
            - github.com/k3d-io/k3d
            - github.com/mittwald/go-helm-client
            - github.com/spf13/cobra
            - github.com/stretchr/testify
            - sigs.k8s.io
            - k8s.io
  exclusions:
    rules:
      - path: "cmd/.+"
        linters:
          - forbidigo
