version: "2"
linters:
  disable:
    - wsl  # deprecated, replaced by wsl_v5
  enable:
    - wsl_v5
  default: all
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    depguard:
      rules:
        main:
          files:
            - "$all"
            - "!$test"
          list-mode: strict
          allow:
            - $gostd
            - github.com/devantler-tech/ksail-go
            - github.com/spf13/cobra
            - github.com/docker/docker
            - github.com/fatih/color
            - github.com/k3d-io/k3d/v5
            - github.com/mittwald/go-helm-client
            - k8s.io/apiextensions-apiserver
            - k8s.io/apimachinery
            - k8s.io/client-go
            - sigs.k8s.io/kind
            - sigs.k8s.io/kustomize
            - sigs.k8s.io/yaml
