version: "2"
run:
  allow-parallel-runners: true
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
linters:
  default: all
  enable:
    - wsl_v5
  disable:
    - exhaustruct
    - wsl
  exclusions:
    paths:
      - ".*mocks.*\\.go$"
    rules:
      - linters:
          - ireturn
        path: pkg/config-manager/helpers/loader.go
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    depguard:
      rules:
        main:
          files:
            - "$all"
            - "!$test"
          list-mode: strict
          allow:
            - $gostd
            - github.com/devantler-tech
            - github.com/docker
            - github.com/fatih/color
            - github.com/gkampitakis/go-snaps
            - github.com/jinzhu/copier
            - github.com/k3d-io
            - github.com/mittwald/go-helm-client
            - github.com/rancher
            - github.com/spf13/cobra
            - github.com/spf13/pflag
            - github.com/spf13/viper
            - github.com/stretchr/testify
            - k8s.io
            - sigs.k8s.io
