version: "2"
run:
  allow-parallel-runners: true
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
linters:
  default: all
  enable:
    - wsl_v5
  disable:
    - exhaustruct
    - wsl
  exclusions:
    paths:
      - ".*mocks.*\\.go$"
    rules:
      - linters:
          - ireturn
        path: pkg/io/config-manager/helpers/loader.go
      - linters:
          - ireturn
        path: pkg/client/docker/engine.go
      - linters:
          - ireturn
        path: cmd/cluster/list_test.go
      - linters:
          - ireturn
        path: pkg/cmd/lifecycle_helpers_test.go
      - linters:
          - ireturn
        path: pkg/svc/provisioner/cluster/factory.go
      - linters:
          - ireturn
        path: cmd/cipher/encrypt.go
      - linters:
          - nlreturn
        path: pkg/scaffolder/scaffolder_test.go
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    depguard:
      rules:
        main:
          files:
            - "$all"
            - "!$test"
          list-mode: strict
          allow:
            - $gostd
            - github.com/devantler-tech
            - github.com/derailed/k9s
            - github.com/fluxcd
            - github.com/getsops/sops
            - github.com/invopop/jsonschema
            - github.com/mitchellh
            - github.com/samber/do/v2
            - github.com/docker
            - github.com/fatih/color
            - github.com/fluxcd
            - github.com/gkampitakis/go-snaps
            - github.com/jinzhu/copier
            - github.com/k3d-io
            - github.com/rancher
            - github.com/mittwald
            - github.com/spf13/cobra
            - github.com/spf13/pflag
            - github.com/spf13/viper
            - github.com/stretchr/testify
            - github.com/sirupsen/logrus
            - helm.sh/helm
            - k8s.io
            - sigs.k8s.io
