version: "2"
linters:
  default: all
  settings:
    depguard:
      rules:
        main:
          files:
            - "$all"
            - "!$test"
          list-mode: strict
          allow:
            - $gostd
            - github.com/devantler-tech/ksail-go
            - github.com/docker/docker
            - github.com/fatih/color
            - github.com/k3d-io/k3d
            - github.com/mittwald/go-helm-client
            - github.com/spf13/cobra
            - github.com/stretchr/testify
            - sigs.k8s.io
            - k8s.io
    exhaustruct:
      exclude:
        - '.+/cobra\.Command$'
        - '.+/types\.Cluster$'
        - '.+/v1alpha1\.Cluster$'
        - '.+/v1alpha1\.Spec$'
        - '.+/v1alpha4\.Cluster$'
        - '.+/v1alpha5\.ClusterConfig$'
        - '.+/v1alpha5\.SimpleConfig$'
        - '.+\.ObjectMeta$'
        - '.+\v1alpha4\.Node$'
        - '.+/v1\.DeleteOptions$'
        - '.+/v1\.GetOptions$'
        - '.+/v1\.CreateOptions$'
        - '.+/v1\.UpdateOptions$'
        - '.+/clientcmd\.ClientConfigLoadingRules$'
        - '.+/clientcmd\.ConfigOverrides$'
        - '.+/helmclient\.ChartSpec$'
        - '.+helmclient\.ChartSpec$'
        - 'github\.com/mittwald/go-helm-client\.ChartSpec$'
        - '.+/helmclient\.Options$'
        - '.+helmclient\.Options$'
        - 'github\.com/mittwald/go-helm-client\.Options$'
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - github.com/mittwald/go-helm-client.Client

  exclusions:
    rules:
      - path: "cmd/.+"
        linters:
          - forbidigo
