version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: default
    formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^build:"
      - "merge conflict"
      - Merge pull request
      - Merge branch
      - go mod tidy
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: devantler-tech
    name: ksail-go
  draft: false
  mode: replace
  header: |
    ## KSail {{ .Tag }} ({{ .Date }})
    
    Welcome to this new release of KSail! 🎉
  footer: |
    ## Docker Images
    
    Docker images are available at:
    - `ghcr.io/devantler-tech/ksail-go:{{ .Tag }}`
    - `ghcr.io/devantler-tech/ksail-go:latest`

    ## Installation
    
    ### Homebrew
    ```bash
    brew install devantler-tech/taps/ksail
    ```
    
    ### Download Binary
    Download the binary for your platform from the assets below.
    
    ### Go Install
    ```bash
    go install github.com/devantler-tech/ksail-go@{{ .Tag }}
    ```

    ---

    **Full Changelog**: https://github.com/devantler-tech/ksail-go/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser) 🚀
