APPLY_FIXES: all
FLAVOR_SUGGESTIONS: false

FILTER_REGEX_EXCLUDE: megalinter-reports/.*
IGNORE_GITIGNORED_FILES: true
EXCLUDED_DIRECTORIES:
  - .specify
  - megalinter-reports
  - report
  - .github/prompts

DISABLE_LINTERS:
  - GO_REVIVE
