APPLY_FIXES: all
FLAVOR_SUGGESTIONS: false

FILTER_REGEX_EXCLUDE: megalinter-reports/.*
IGNORE_GITIGNORED_FILES: true
EXCLUDED_DIRECTORIES:
  - .specify
  - megalinter-reports
  - report
  - .github/agents
  - .github/prompts
  - .jscpd

REPORTERS_MARKDOWN_SUMMARY_TYPE: sections
GO_GOLANGCI_LINT_PRE_COMMANDS:
  - command: cd src
GO_GOLANGCI_LINT_ARGUMENTS: ["--config=.golangci.yml", "./..."]
DISABLE_LINTERS:
  - GO_REVIVE
  - REPOSITORY_GITLEAKS
  - REPOSITORY_SECRETLINT
  - SPELL_CSPELL

MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: .github/(agents|prompts)
MARKDOWN_MARKDOWN_TABLE_FORMATTER_FILTER_REGEX_EXCLUDE: .github/(agents|prompts)
