APPLY_FIXES: all
FLAVOR_SUGGESTIONS: false

FILTER_REGEX_EXCLUDE: megalinter-reports/.*
IGNORE_GITIGNORED_FILES: true
EXCLUDED_DIRECTORIES:
  - .specify
  - megalinter-reports
  - report
  - .github/agents
  - .github/prompts
  - .jscpd
  - schemas

REPORTERS_MARKDOWN_SUMMARY_TYPE: sections
DISABLE_LINTERS:
  - GO_GOLANGCI_LINT # Disabled: MegaLinter container has Go 1.24.7, but project requires Go 1.25.4. CI runs golangci-lint separately with correct Go version.
  - GO_REVIVE
  - REPOSITORY_GITLEAKS
  - REPOSITORY_SECRETLINT
  - SPELL_CSPELL

MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: .github/(agents|prompts)
MARKDOWN_MARKDOWN_TABLE_FORMATTER_FILTER_REGEX_EXCLUDE: .github/(agents|prompts)
MARKDOWN_LYCHEE_FILTER_REGEX_EXCLUDE: .github/copilot-instructions\.md
