APPLY_FIXES: all
APPLY_FIXES_EVENT: pull_request
APPLY_FIXES_MODE: commit
FLAVOR_SUGGESTIONS: false

FILTER_REGEX_EXCLUDE: megalinter-reports/.*
IGNORE_GITIGNORED_FILES: true
EXCLUDED_DIRECTORIES:
  - .specify
  - megalinter-reports
  - report
  - .github/agents
  - .github/prompts
  - .jscpd

REPORTERS_MARKDOWN_SUMMARY_TYPE: sections

DISABLE_LINTERS:
  - GO_GOLANGCI_LINT
  - GO_REVIVE
  - REPOSITORY_GITLEAKS
  - REPOSITORY_SECRETLINT
  - SPELL_CSPELL

MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: .github/(agents|prompts)
