recursive: true

packages:
  github.com/devantler-tech/ksail-go:
    config:
      all: true
  github.com/docker/docker/client:
    config:
      recursive: false
    interfaces:
      ContainerAPIClient:
        config:
          dir: pkg/provisioner/cluster/kind
          filename: mocks_containerapiclient_test.go
          pkgname: kindprovisioner
      APIClient:
        config:
          dir: pkg/provisioner/container_engine/docker
          filename: mocks_apiclient_test.go
          pkgname: dockerprovisioner
