recursive: true

packages:
  github.com/devantler-tech/ksail-go:
    config:
      all: true
  github.com/docker/docker/client:
    config:
      recursive: false
      dir: pkg/provisioner
      filename: mocks_test.go
      pkgname: provisioner
    interfaces:
      ContainerAPIClient:
      APIClient:
