recursive: true

packages:
  github.com/devantler-tech/ksail-go:
    config:
      all: true
  github.com/devantler-tech/ksail-go/pkg/config-manager:
    config:
      recursive: false
      dir: pkg/config-manager
      filename: mocks.go
      pkgname: configmanager
    interfaces:
      ConfigManager:
  github.com/devantler-tech/ksail-go/pkg/provisioner/cluster:
    config:
      recursive: false
      dir: pkg/provisioner/cluster
      filename: mocks.go
      pkgname: clusterprovisioner
    interfaces:
      ClusterProvisioner:
      Factory:
  github.com/devantler-tech/ksail-go/pkg/validator:
    config:
      recursive: false
      dir: pkg/validator
      filename: mocks.go
      pkgname: validator
    interfaces:
      Validator:
  github.com/docker/docker/client:
    config:
      recursive: false
      dir: pkg/containerengine
      filename: mocks.go
      pkgname: containerengine
    interfaces:
      ContainerAPIClient:
      APIClient:
  k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1:
    config:
      recursive: false
      dir: pkg/installer/kubectl
      filename: apiextensions_mocks_test.go
      pkgname: kubectlinstaller
    interfaces:
      CustomResourceDefinitionInterface:
  k8s.io/client-go/dynamic:
    config:
      recursive: false
      dir: pkg/installer/kubectl
      filename: dynamic_mocks_test.go
      pkgname: kubectlinstaller
    interfaces:
      ResourceInterface:
