// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package providerprovisioner

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockProviderProvisioner creates a new instance of MockProviderProvisioner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderProvisioner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderProvisioner {
	mock := &MockProviderProvisioner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProviderProvisioner is an autogenerated mock type for the ProviderProvisioner type
type MockProviderProvisioner struct {
	mock.Mock
}

type MockProviderProvisioner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProviderProvisioner) EXPECT() *MockProviderProvisioner_Expecter {
	return &MockProviderProvisioner_Expecter{mock: &_m.Mock}
}

// CheckReady provides a mock function for the type MockProviderProvisioner
func (_mock *MockProviderProvisioner) CheckReady() (bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CheckReady")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProviderProvisioner_CheckReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckReady'
type MockProviderProvisioner_CheckReady_Call struct {
	*mock.Call
}

// CheckReady is a helper method to define mock.On call
func (_e *MockProviderProvisioner_Expecter) CheckReady() *MockProviderProvisioner_CheckReady_Call {
	return &MockProviderProvisioner_CheckReady_Call{Call: _e.mock.On("CheckReady")}
}

func (_c *MockProviderProvisioner_CheckReady_Call) Run(run func()) *MockProviderProvisioner_CheckReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProviderProvisioner_CheckReady_Call) Return(b bool, err error) *MockProviderProvisioner_CheckReady_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockProviderProvisioner_CheckReady_Call) RunAndReturn(run func() (bool, error)) *MockProviderProvisioner_CheckReady_Call {
	_c.Call.Return(run)
	return _c
}
