// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cluster

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMockcniInstaller creates a new instance of mockcniInstaller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockcniInstaller(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockcniInstaller {
	mock := &mockcniInstaller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockcniInstaller is an autogenerated mock type for the cniInstaller type
type mockcniInstaller struct {
	mock.Mock
}

type mockcniInstaller_Expecter struct {
	mock *mock.Mock
}

func (_m *mockcniInstaller) EXPECT() *mockcniInstaller_Expecter {
	return &mockcniInstaller_Expecter{mock: &_m.Mock}
}

// Install provides a mock function for the type mockcniInstaller
func (_mock *mockcniInstaller) Install(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Install")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockcniInstaller_Install_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Install'
type mockcniInstaller_Install_Call struct {
	*mock.Call
}

// Install is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockcniInstaller_Expecter) Install(ctx interface{}) *mockcniInstaller_Install_Call {
	return &mockcniInstaller_Install_Call{Call: _e.mock.On("Install", ctx)}
}

func (_c *mockcniInstaller_Install_Call) Run(run func(ctx context.Context)) *mockcniInstaller_Install_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockcniInstaller_Install_Call) Return(err error) *mockcniInstaller_Install_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockcniInstaller_Install_Call) RunAndReturn(run func(ctx context.Context) error) *mockcniInstaller_Install_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForReadiness provides a mock function for the type mockcniInstaller
func (_mock *mockcniInstaller) WaitForReadiness(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WaitForReadiness")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockcniInstaller_WaitForReadiness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForReadiness'
type mockcniInstaller_WaitForReadiness_Call struct {
	*mock.Call
}

// WaitForReadiness is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockcniInstaller_Expecter) WaitForReadiness(ctx interface{}) *mockcniInstaller_WaitForReadiness_Call {
	return &mockcniInstaller_WaitForReadiness_Call{Call: _e.mock.On("WaitForReadiness", ctx)}
}

func (_c *mockcniInstaller_WaitForReadiness_Call) Run(run func(ctx context.Context)) *mockcniInstaller_WaitForReadiness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockcniInstaller_WaitForReadiness_Call) Return(err error) *mockcniInstaller_WaitForReadiness_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockcniInstaller_WaitForReadiness_Call) RunAndReturn(run func(ctx context.Context) error) *mockcniInstaller_WaitForReadiness_Call {
	_c.Call.Return(run)
	return _c
}
