name: Use KSail Artifact
description: Download the KSail workflow artifact, verify checksum, and run a smoke command.
author: Devantler Tech Platform Team

inputs:
  artifact-name:
    description: Name of the artifact to download.
    required: true
  artifact-checksum:
    description: Expected SHA256 checksum of the binary. When omitted, checksum verification is skipped.
    required: false
    default: ""
  download-path:
    description: Destination directory for the downloaded artifact.
    required: false
    default: ./bin
  binary-name:
    description: Binary filename to mark executable and reference in smoke checks.
    required: false
    default: ksail
  smoke-command:
    description: Command to run after download. Defaults to "<download-path>/<binary-name> --version" when empty.
    required: false
    default: ""

outputs:
  binary-path:
    description: Absolute path to the downloaded binary.
    value: ${{ steps.prepare.outputs.binary-path }}

runs:
  using: composite
  steps:
    - name: Download artifact
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        name: ${{ inputs['artifact-name'] }}
        path: ${{ inputs['download-path'] }}

    - name: Prepare binary
      id: prepare
      shell: bash
      env:
        DOWNLOAD_PATH: ${{ inputs['download-path'] }}
        BINARY_NAME: ${{ inputs['binary-name'] }}
      run: |
        set -Eeuo pipefail
        bin_path="$DOWNLOAD_PATH/$BINARY_NAME"
        if [ ! -f "$bin_path" ]; then
          echo "Expected artifact binary not found at $bin_path" >&2
          ls -R "$DOWNLOAD_PATH" || true
          exit 1
        fi
        chmod +x "$bin_path"
        echo "binary-path=$bin_path" >> "$GITHUB_OUTPUT"

    - name: Verify checksum
      if: inputs['artifact-checksum'] != ''
      shell: bash
      env:
        DOWNLOAD_PATH: ${{ inputs['download-path'] }}
        BINARY_NAME: ${{ inputs['binary-name'] }}
        EXPECTED_CHECKSUM: ${{ inputs['artifact-checksum'] }}
      run: |
        set -Eeuo pipefail
        bin_path="$DOWNLOAD_PATH/$BINARY_NAME"
        expected="$EXPECTED_CHECKSUM"
        actual=$(shasum -a 256 "$bin_path" | awk '{print $1}')
        if [ "$actual" != "$expected" ]; then
          echo "Checksum mismatch for $bin_path" >&2
          echo "Expected: $expected" >&2
          echo "Actual:   $actual" >&2
          exit 1
        fi

    - name: Run smoke command
      shell: bash
      env:
        DOWNLOAD_PATH: ${{ inputs['download-path'] }}
        BINARY_NAME: ${{ inputs['binary-name'] }}
        SMOKE_COMMAND: ${{ inputs['smoke-command'] }}
      run: |
        set -Eeuo pipefail
        bin_path="$DOWNLOAD_PATH/$BINARY_NAME"
        if [ -n "$SMOKE_COMMAND" ]; then
          cmd="$SMOKE_COMMAND"
        else
          cmd="$bin_path --version"
        fi
        echo "Executing smoke command: $cmd"
        bash -lc "$cmd"
