// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cipher

import (
	"github.com/getsops/sops/v3"
	mock "github.com/stretchr/testify/mock"
)

// newMockstoreWithExample creates a new instance of mockstoreWithExample. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstoreWithExample(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstoreWithExample {
	mock := &mockstoreWithExample{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstoreWithExample is an autogenerated mock type for the storeWithExample type
type mockstoreWithExample struct {
	mock.Mock
}

type mockstoreWithExample_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstoreWithExample) EXPECT() *mockstoreWithExample_Expecter {
	return &mockstoreWithExample_Expecter{mock: &_m.Mock}
}

// EmitEncryptedFile provides a mock function for the type mockstoreWithExample
func (_mock *mockstoreWithExample) EmitEncryptedFile(tree sops.Tree) ([]byte, error) {
	ret := _mock.Called(tree)

	if len(ret) == 0 {
		panic("no return value specified for EmitEncryptedFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(sops.Tree) ([]byte, error)); ok {
		return returnFunc(tree)
	}
	if returnFunc, ok := ret.Get(0).(func(sops.Tree) []byte); ok {
		r0 = returnFunc(tree)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(sops.Tree) error); ok {
		r1 = returnFunc(tree)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstoreWithExample_EmitEncryptedFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmitEncryptedFile'
type mockstoreWithExample_EmitEncryptedFile_Call struct {
	*mock.Call
}

// EmitEncryptedFile is a helper method to define mock.On call
//   - tree sops.Tree
func (_e *mockstoreWithExample_Expecter) EmitEncryptedFile(tree interface{}) *mockstoreWithExample_EmitEncryptedFile_Call {
	return &mockstoreWithExample_EmitEncryptedFile_Call{Call: _e.mock.On("EmitEncryptedFile", tree)}
}

func (_c *mockstoreWithExample_EmitEncryptedFile_Call) Run(run func(tree sops.Tree)) *mockstoreWithExample_EmitEncryptedFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sops.Tree
		if args[0] != nil {
			arg0 = args[0].(sops.Tree)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockstoreWithExample_EmitEncryptedFile_Call) Return(bytes []byte, err error) *mockstoreWithExample_EmitEncryptedFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *mockstoreWithExample_EmitEncryptedFile_Call) RunAndReturn(run func(tree sops.Tree) ([]byte, error)) *mockstoreWithExample_EmitEncryptedFile_Call {
	_c.Call.Return(run)
	return _c
}

// EmitExample provides a mock function for the type mockstoreWithExample
func (_mock *mockstoreWithExample) EmitExample() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EmitExample")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// mockstoreWithExample_EmitExample_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmitExample'
type mockstoreWithExample_EmitExample_Call struct {
	*mock.Call
}

// EmitExample is a helper method to define mock.On call
func (_e *mockstoreWithExample_Expecter) EmitExample() *mockstoreWithExample_EmitExample_Call {
	return &mockstoreWithExample_EmitExample_Call{Call: _e.mock.On("EmitExample")}
}

func (_c *mockstoreWithExample_EmitExample_Call) Run(run func()) *mockstoreWithExample_EmitExample_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockstoreWithExample_EmitExample_Call) Return(bytes []byte) *mockstoreWithExample_EmitExample_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *mockstoreWithExample_EmitExample_Call) RunAndReturn(run func() []byte) *mockstoreWithExample_EmitExample_Call {
	_c.Call.Return(run)
	return _c
}

// EmitPlainFile provides a mock function for the type mockstoreWithExample
func (_mock *mockstoreWithExample) EmitPlainFile(treeBranches sops.TreeBranches) ([]byte, error) {
	ret := _mock.Called(treeBranches)

	if len(ret) == 0 {
		panic("no return value specified for EmitPlainFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(sops.TreeBranches) ([]byte, error)); ok {
		return returnFunc(treeBranches)
	}
	if returnFunc, ok := ret.Get(0).(func(sops.TreeBranches) []byte); ok {
		r0 = returnFunc(treeBranches)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(sops.TreeBranches) error); ok {
		r1 = returnFunc(treeBranches)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstoreWithExample_EmitPlainFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmitPlainFile'
type mockstoreWithExample_EmitPlainFile_Call struct {
	*mock.Call
}

// EmitPlainFile is a helper method to define mock.On call
//   - treeBranches sops.TreeBranches
func (_e *mockstoreWithExample_Expecter) EmitPlainFile(treeBranches interface{}) *mockstoreWithExample_EmitPlainFile_Call {
	return &mockstoreWithExample_EmitPlainFile_Call{Call: _e.mock.On("EmitPlainFile", treeBranches)}
}

func (_c *mockstoreWithExample_EmitPlainFile_Call) Run(run func(treeBranches sops.TreeBranches)) *mockstoreWithExample_EmitPlainFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sops.TreeBranches
		if args[0] != nil {
			arg0 = args[0].(sops.TreeBranches)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockstoreWithExample_EmitPlainFile_Call) Return(bytes []byte, err error) *mockstoreWithExample_EmitPlainFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *mockstoreWithExample_EmitPlainFile_Call) RunAndReturn(run func(treeBranches sops.TreeBranches) ([]byte, error)) *mockstoreWithExample_EmitPlainFile_Call {
	_c.Call.Return(run)
	return _c
}

// EmitValue provides a mock function for the type mockstoreWithExample
func (_mock *mockstoreWithExample) EmitValue(ifaceVal interface{}) ([]byte, error) {
	ret := _mock.Called(ifaceVal)

	if len(ret) == 0 {
		panic("no return value specified for EmitValue")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(interface{}) ([]byte, error)); ok {
		return returnFunc(ifaceVal)
	}
	if returnFunc, ok := ret.Get(0).(func(interface{}) []byte); ok {
		r0 = returnFunc(ifaceVal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = returnFunc(ifaceVal)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstoreWithExample_EmitValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmitValue'
type mockstoreWithExample_EmitValue_Call struct {
	*mock.Call
}

// EmitValue is a helper method to define mock.On call
//   - ifaceVal interface{}
func (_e *mockstoreWithExample_Expecter) EmitValue(ifaceVal interface{}) *mockstoreWithExample_EmitValue_Call {
	return &mockstoreWithExample_EmitValue_Call{Call: _e.mock.On("EmitValue", ifaceVal)}
}

func (_c *mockstoreWithExample_EmitValue_Call) Run(run func(ifaceVal interface{})) *mockstoreWithExample_EmitValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockstoreWithExample_EmitValue_Call) Return(bytes []byte, err error) *mockstoreWithExample_EmitValue_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *mockstoreWithExample_EmitValue_Call) RunAndReturn(run func(ifaceVal interface{}) ([]byte, error)) *mockstoreWithExample_EmitValue_Call {
	_c.Call.Return(run)
	return _c
}

// HasSopsTopLevelKey provides a mock function for the type mockstoreWithExample
func (_mock *mockstoreWithExample) HasSopsTopLevelKey(treeBranch sops.TreeBranch) bool {
	ret := _mock.Called(treeBranch)

	if len(ret) == 0 {
		panic("no return value specified for HasSopsTopLevelKey")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(sops.TreeBranch) bool); ok {
		r0 = returnFunc(treeBranch)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// mockstoreWithExample_HasSopsTopLevelKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasSopsTopLevelKey'
type mockstoreWithExample_HasSopsTopLevelKey_Call struct {
	*mock.Call
}

// HasSopsTopLevelKey is a helper method to define mock.On call
//   - treeBranch sops.TreeBranch
func (_e *mockstoreWithExample_Expecter) HasSopsTopLevelKey(treeBranch interface{}) *mockstoreWithExample_HasSopsTopLevelKey_Call {
	return &mockstoreWithExample_HasSopsTopLevelKey_Call{Call: _e.mock.On("HasSopsTopLevelKey", treeBranch)}
}

func (_c *mockstoreWithExample_HasSopsTopLevelKey_Call) Run(run func(treeBranch sops.TreeBranch)) *mockstoreWithExample_HasSopsTopLevelKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sops.TreeBranch
		if args[0] != nil {
			arg0 = args[0].(sops.TreeBranch)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockstoreWithExample_HasSopsTopLevelKey_Call) Return(b bool) *mockstoreWithExample_HasSopsTopLevelKey_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *mockstoreWithExample_HasSopsTopLevelKey_Call) RunAndReturn(run func(treeBranch sops.TreeBranch) bool) *mockstoreWithExample_HasSopsTopLevelKey_Call {
	_c.Call.Return(run)
	return _c
}

// LoadEncryptedFile provides a mock function for the type mockstoreWithExample
func (_mock *mockstoreWithExample) LoadEncryptedFile(in []byte) (sops.Tree, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for LoadEncryptedFile")
	}

	var r0 sops.Tree
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (sops.Tree, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) sops.Tree); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(sops.Tree)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstoreWithExample_LoadEncryptedFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadEncryptedFile'
type mockstoreWithExample_LoadEncryptedFile_Call struct {
	*mock.Call
}

// LoadEncryptedFile is a helper method to define mock.On call
//   - in []byte
func (_e *mockstoreWithExample_Expecter) LoadEncryptedFile(in interface{}) *mockstoreWithExample_LoadEncryptedFile_Call {
	return &mockstoreWithExample_LoadEncryptedFile_Call{Call: _e.mock.On("LoadEncryptedFile", in)}
}

func (_c *mockstoreWithExample_LoadEncryptedFile_Call) Run(run func(in []byte)) *mockstoreWithExample_LoadEncryptedFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockstoreWithExample_LoadEncryptedFile_Call) Return(tree sops.Tree, err error) *mockstoreWithExample_LoadEncryptedFile_Call {
	_c.Call.Return(tree, err)
	return _c
}

func (_c *mockstoreWithExample_LoadEncryptedFile_Call) RunAndReturn(run func(in []byte) (sops.Tree, error)) *mockstoreWithExample_LoadEncryptedFile_Call {
	_c.Call.Return(run)
	return _c
}

// LoadPlainFile provides a mock function for the type mockstoreWithExample
func (_mock *mockstoreWithExample) LoadPlainFile(in []byte) (sops.TreeBranches, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for LoadPlainFile")
	}

	var r0 sops.TreeBranches
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (sops.TreeBranches, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) sops.TreeBranches); ok {
		r0 = returnFunc(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sops.TreeBranches)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstoreWithExample_LoadPlainFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadPlainFile'
type mockstoreWithExample_LoadPlainFile_Call struct {
	*mock.Call
}

// LoadPlainFile is a helper method to define mock.On call
//   - in []byte
func (_e *mockstoreWithExample_Expecter) LoadPlainFile(in interface{}) *mockstoreWithExample_LoadPlainFile_Call {
	return &mockstoreWithExample_LoadPlainFile_Call{Call: _e.mock.On("LoadPlainFile", in)}
}

func (_c *mockstoreWithExample_LoadPlainFile_Call) Run(run func(in []byte)) *mockstoreWithExample_LoadPlainFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockstoreWithExample_LoadPlainFile_Call) Return(treeBranches sops.TreeBranches, err error) *mockstoreWithExample_LoadPlainFile_Call {
	_c.Call.Return(treeBranches, err)
	return _c
}

func (_c *mockstoreWithExample_LoadPlainFile_Call) RunAndReturn(run func(in []byte) (sops.TreeBranches, error)) *mockstoreWithExample_LoadPlainFile_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type mockstoreWithExample
func (_mock *mockstoreWithExample) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockstoreWithExample_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type mockstoreWithExample_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *mockstoreWithExample_Expecter) Name() *mockstoreWithExample_Name_Call {
	return &mockstoreWithExample_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *mockstoreWithExample_Name_Call) Run(run func()) *mockstoreWithExample_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockstoreWithExample_Name_Call) Return(s string) *mockstoreWithExample_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mockstoreWithExample_Name_Call) RunAndReturn(run func() string) *mockstoreWithExample_Name_Call {
	_c.Call.Return(run)
	return _c
}
