// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package k3dprovisioner

import (
	"context"

	"github.com/k3d-io/k3d/v5/pkg/config/v1alpha5"
	"github.com/k3d-io/k3d/v5/pkg/runtimes"
	"github.com/k3d-io/k3d/v5/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockK3dClientProvider creates a new instance of MockK3dClientProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockK3dClientProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockK3dClientProvider {
	mock := &MockK3dClientProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockK3dClientProvider is an autogenerated mock type for the K3dClientProvider type
type MockK3dClientProvider struct {
	mock.Mock
}

type MockK3dClientProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockK3dClientProvider) EXPECT() *MockK3dClientProvider_Expecter {
	return &MockK3dClientProvider_Expecter{mock: &_m.Mock}
}

// ClusterDelete provides a mock function for the type MockK3dClientProvider
func (_mock *MockK3dClientProvider) ClusterDelete(ctx context.Context, runtime runtimes.Runtime, cluster *types.Cluster, opts types.ClusterDeleteOpts) error {
	ret := _mock.Called(ctx, runtime, cluster, opts)

	if len(ret) == 0 {
		panic("no return value specified for ClusterDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, runtimes.Runtime, *types.Cluster, types.ClusterDeleteOpts) error); ok {
		r0 = returnFunc(ctx, runtime, cluster, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockK3dClientProvider_ClusterDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterDelete'
type MockK3dClientProvider_ClusterDelete_Call struct {
	*mock.Call
}

// ClusterDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - runtime runtimes.Runtime
//   - cluster *types.Cluster
//   - opts types.ClusterDeleteOpts
func (_e *MockK3dClientProvider_Expecter) ClusterDelete(ctx interface{}, runtime interface{}, cluster interface{}, opts interface{}) *MockK3dClientProvider_ClusterDelete_Call {
	return &MockK3dClientProvider_ClusterDelete_Call{Call: _e.mock.On("ClusterDelete", ctx, runtime, cluster, opts)}
}

func (_c *MockK3dClientProvider_ClusterDelete_Call) Run(run func(ctx context.Context, runtime runtimes.Runtime, cluster *types.Cluster, opts types.ClusterDeleteOpts)) *MockK3dClientProvider_ClusterDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 runtimes.Runtime
		if args[1] != nil {
			arg1 = args[1].(runtimes.Runtime)
		}
		var arg2 *types.Cluster
		if args[2] != nil {
			arg2 = args[2].(*types.Cluster)
		}
		var arg3 types.ClusterDeleteOpts
		if args[3] != nil {
			arg3 = args[3].(types.ClusterDeleteOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockK3dClientProvider_ClusterDelete_Call) Return(err error) *MockK3dClientProvider_ClusterDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockK3dClientProvider_ClusterDelete_Call) RunAndReturn(run func(ctx context.Context, runtime runtimes.Runtime, cluster *types.Cluster, opts types.ClusterDeleteOpts) error) *MockK3dClientProvider_ClusterDelete_Call {
	_c.Call.Return(run)
	return _c
}

// ClusterGet provides a mock function for the type MockK3dClientProvider
func (_mock *MockK3dClientProvider) ClusterGet(ctx context.Context, runtime runtimes.Runtime, cluster *types.Cluster) (*types.Cluster, error) {
	ret := _mock.Called(ctx, runtime, cluster)

	if len(ret) == 0 {
		panic("no return value specified for ClusterGet")
	}

	var r0 *types.Cluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, runtimes.Runtime, *types.Cluster) (*types.Cluster, error)); ok {
		return returnFunc(ctx, runtime, cluster)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, runtimes.Runtime, *types.Cluster) *types.Cluster); ok {
		r0 = returnFunc(ctx, runtime, cluster)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Cluster)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, runtimes.Runtime, *types.Cluster) error); ok {
		r1 = returnFunc(ctx, runtime, cluster)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockK3dClientProvider_ClusterGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterGet'
type MockK3dClientProvider_ClusterGet_Call struct {
	*mock.Call
}

// ClusterGet is a helper method to define mock.On call
//   - ctx context.Context
//   - runtime runtimes.Runtime
//   - cluster *types.Cluster
func (_e *MockK3dClientProvider_Expecter) ClusterGet(ctx interface{}, runtime interface{}, cluster interface{}) *MockK3dClientProvider_ClusterGet_Call {
	return &MockK3dClientProvider_ClusterGet_Call{Call: _e.mock.On("ClusterGet", ctx, runtime, cluster)}
}

func (_c *MockK3dClientProvider_ClusterGet_Call) Run(run func(ctx context.Context, runtime runtimes.Runtime, cluster *types.Cluster)) *MockK3dClientProvider_ClusterGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 runtimes.Runtime
		if args[1] != nil {
			arg1 = args[1].(runtimes.Runtime)
		}
		var arg2 *types.Cluster
		if args[2] != nil {
			arg2 = args[2].(*types.Cluster)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockK3dClientProvider_ClusterGet_Call) Return(cluster1 *types.Cluster, err error) *MockK3dClientProvider_ClusterGet_Call {
	_c.Call.Return(cluster1, err)
	return _c
}

func (_c *MockK3dClientProvider_ClusterGet_Call) RunAndReturn(run func(ctx context.Context, runtime runtimes.Runtime, cluster *types.Cluster) (*types.Cluster, error)) *MockK3dClientProvider_ClusterGet_Call {
	_c.Call.Return(run)
	return _c
}

// ClusterList provides a mock function for the type MockK3dClientProvider
func (_mock *MockK3dClientProvider) ClusterList(ctx context.Context, runtime runtimes.Runtime) ([]*types.Cluster, error) {
	ret := _mock.Called(ctx, runtime)

	if len(ret) == 0 {
		panic("no return value specified for ClusterList")
	}

	var r0 []*types.Cluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, runtimes.Runtime) ([]*types.Cluster, error)); ok {
		return returnFunc(ctx, runtime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, runtimes.Runtime) []*types.Cluster); ok {
		r0 = returnFunc(ctx, runtime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.Cluster)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, runtimes.Runtime) error); ok {
		r1 = returnFunc(ctx, runtime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockK3dClientProvider_ClusterList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterList'
type MockK3dClientProvider_ClusterList_Call struct {
	*mock.Call
}

// ClusterList is a helper method to define mock.On call
//   - ctx context.Context
//   - runtime runtimes.Runtime
func (_e *MockK3dClientProvider_Expecter) ClusterList(ctx interface{}, runtime interface{}) *MockK3dClientProvider_ClusterList_Call {
	return &MockK3dClientProvider_ClusterList_Call{Call: _e.mock.On("ClusterList", ctx, runtime)}
}

func (_c *MockK3dClientProvider_ClusterList_Call) Run(run func(ctx context.Context, runtime runtimes.Runtime)) *MockK3dClientProvider_ClusterList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 runtimes.Runtime
		if args[1] != nil {
			arg1 = args[1].(runtimes.Runtime)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockK3dClientProvider_ClusterList_Call) Return(clusters []*types.Cluster, err error) *MockK3dClientProvider_ClusterList_Call {
	_c.Call.Return(clusters, err)
	return _c
}

func (_c *MockK3dClientProvider_ClusterList_Call) RunAndReturn(run func(ctx context.Context, runtime runtimes.Runtime) ([]*types.Cluster, error)) *MockK3dClientProvider_ClusterList_Call {
	_c.Call.Return(run)
	return _c
}

// ClusterRun provides a mock function for the type MockK3dClientProvider
func (_mock *MockK3dClientProvider) ClusterRun(ctx context.Context, runtime runtimes.Runtime, clusterConfig *v1alpha5.ClusterConfig) error {
	ret := _mock.Called(ctx, runtime, clusterConfig)

	if len(ret) == 0 {
		panic("no return value specified for ClusterRun")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, runtimes.Runtime, *v1alpha5.ClusterConfig) error); ok {
		r0 = returnFunc(ctx, runtime, clusterConfig)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockK3dClientProvider_ClusterRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterRun'
type MockK3dClientProvider_ClusterRun_Call struct {
	*mock.Call
}

// ClusterRun is a helper method to define mock.On call
//   - ctx context.Context
//   - runtime runtimes.Runtime
//   - clusterConfig *v1alpha5.ClusterConfig
func (_e *MockK3dClientProvider_Expecter) ClusterRun(ctx interface{}, runtime interface{}, clusterConfig interface{}) *MockK3dClientProvider_ClusterRun_Call {
	return &MockK3dClientProvider_ClusterRun_Call{Call: _e.mock.On("ClusterRun", ctx, runtime, clusterConfig)}
}

func (_c *MockK3dClientProvider_ClusterRun_Call) Run(run func(ctx context.Context, runtime runtimes.Runtime, clusterConfig *v1alpha5.ClusterConfig)) *MockK3dClientProvider_ClusterRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 runtimes.Runtime
		if args[1] != nil {
			arg1 = args[1].(runtimes.Runtime)
		}
		var arg2 *v1alpha5.ClusterConfig
		if args[2] != nil {
			arg2 = args[2].(*v1alpha5.ClusterConfig)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockK3dClientProvider_ClusterRun_Call) Return(err error) *MockK3dClientProvider_ClusterRun_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockK3dClientProvider_ClusterRun_Call) RunAndReturn(run func(ctx context.Context, runtime runtimes.Runtime, clusterConfig *v1alpha5.ClusterConfig) error) *MockK3dClientProvider_ClusterRun_Call {
	_c.Call.Return(run)
	return _c
}

// ClusterStart provides a mock function for the type MockK3dClientProvider
func (_mock *MockK3dClientProvider) ClusterStart(ctx context.Context, runtime runtimes.Runtime, cluster *types.Cluster, opts types.ClusterStartOpts) error {
	ret := _mock.Called(ctx, runtime, cluster, opts)

	if len(ret) == 0 {
		panic("no return value specified for ClusterStart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, runtimes.Runtime, *types.Cluster, types.ClusterStartOpts) error); ok {
		r0 = returnFunc(ctx, runtime, cluster, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockK3dClientProvider_ClusterStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterStart'
type MockK3dClientProvider_ClusterStart_Call struct {
	*mock.Call
}

// ClusterStart is a helper method to define mock.On call
//   - ctx context.Context
//   - runtime runtimes.Runtime
//   - cluster *types.Cluster
//   - opts types.ClusterStartOpts
func (_e *MockK3dClientProvider_Expecter) ClusterStart(ctx interface{}, runtime interface{}, cluster interface{}, opts interface{}) *MockK3dClientProvider_ClusterStart_Call {
	return &MockK3dClientProvider_ClusterStart_Call{Call: _e.mock.On("ClusterStart", ctx, runtime, cluster, opts)}
}

func (_c *MockK3dClientProvider_ClusterStart_Call) Run(run func(ctx context.Context, runtime runtimes.Runtime, cluster *types.Cluster, opts types.ClusterStartOpts)) *MockK3dClientProvider_ClusterStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 runtimes.Runtime
		if args[1] != nil {
			arg1 = args[1].(runtimes.Runtime)
		}
		var arg2 *types.Cluster
		if args[2] != nil {
			arg2 = args[2].(*types.Cluster)
		}
		var arg3 types.ClusterStartOpts
		if args[3] != nil {
			arg3 = args[3].(types.ClusterStartOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockK3dClientProvider_ClusterStart_Call) Return(err error) *MockK3dClientProvider_ClusterStart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockK3dClientProvider_ClusterStart_Call) RunAndReturn(run func(ctx context.Context, runtime runtimes.Runtime, cluster *types.Cluster, opts types.ClusterStartOpts) error) *MockK3dClientProvider_ClusterStart_Call {
	_c.Call.Return(run)
	return _c
}

// ClusterStop provides a mock function for the type MockK3dClientProvider
func (_mock *MockK3dClientProvider) ClusterStop(ctx context.Context, runtime runtimes.Runtime, cluster *types.Cluster) error {
	ret := _mock.Called(ctx, runtime, cluster)

	if len(ret) == 0 {
		panic("no return value specified for ClusterStop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, runtimes.Runtime, *types.Cluster) error); ok {
		r0 = returnFunc(ctx, runtime, cluster)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockK3dClientProvider_ClusterStop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterStop'
type MockK3dClientProvider_ClusterStop_Call struct {
	*mock.Call
}

// ClusterStop is a helper method to define mock.On call
//   - ctx context.Context
//   - runtime runtimes.Runtime
//   - cluster *types.Cluster
func (_e *MockK3dClientProvider_Expecter) ClusterStop(ctx interface{}, runtime interface{}, cluster interface{}) *MockK3dClientProvider_ClusterStop_Call {
	return &MockK3dClientProvider_ClusterStop_Call{Call: _e.mock.On("ClusterStop", ctx, runtime, cluster)}
}

func (_c *MockK3dClientProvider_ClusterStop_Call) Run(run func(ctx context.Context, runtime runtimes.Runtime, cluster *types.Cluster)) *MockK3dClientProvider_ClusterStop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 runtimes.Runtime
		if args[1] != nil {
			arg1 = args[1].(runtimes.Runtime)
		}
		var arg2 *types.Cluster
		if args[2] != nil {
			arg2 = args[2].(*types.Cluster)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockK3dClientProvider_ClusterStop_Call) Return(err error) *MockK3dClientProvider_ClusterStop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockK3dClientProvider_ClusterStop_Call) RunAndReturn(run func(ctx context.Context, runtime runtimes.Runtime, cluster *types.Cluster) error) *MockK3dClientProvider_ClusterStop_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockK3dConfigProvider creates a new instance of MockK3dConfigProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockK3dConfigProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockK3dConfigProvider {
	mock := &MockK3dConfigProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockK3dConfigProvider is an autogenerated mock type for the K3dConfigProvider type
type MockK3dConfigProvider struct {
	mock.Mock
}

type MockK3dConfigProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockK3dConfigProvider) EXPECT() *MockK3dConfigProvider_Expecter {
	return &MockK3dConfigProvider_Expecter{mock: &_m.Mock}
}

// TransformSimpleToClusterConfig provides a mock function for the type MockK3dConfigProvider
func (_mock *MockK3dConfigProvider) TransformSimpleToClusterConfig(ctx context.Context, runtime runtimes.Runtime, simpleConfig v1alpha5.SimpleConfig, filename string) (*v1alpha5.ClusterConfig, error) {
	ret := _mock.Called(ctx, runtime, simpleConfig, filename)

	if len(ret) == 0 {
		panic("no return value specified for TransformSimpleToClusterConfig")
	}

	var r0 *v1alpha5.ClusterConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, runtimes.Runtime, v1alpha5.SimpleConfig, string) (*v1alpha5.ClusterConfig, error)); ok {
		return returnFunc(ctx, runtime, simpleConfig, filename)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, runtimes.Runtime, v1alpha5.SimpleConfig, string) *v1alpha5.ClusterConfig); ok {
		r0 = returnFunc(ctx, runtime, simpleConfig, filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha5.ClusterConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, runtimes.Runtime, v1alpha5.SimpleConfig, string) error); ok {
		r1 = returnFunc(ctx, runtime, simpleConfig, filename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockK3dConfigProvider_TransformSimpleToClusterConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransformSimpleToClusterConfig'
type MockK3dConfigProvider_TransformSimpleToClusterConfig_Call struct {
	*mock.Call
}

// TransformSimpleToClusterConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - runtime runtimes.Runtime
//   - simpleConfig v1alpha5.SimpleConfig
//   - filename string
func (_e *MockK3dConfigProvider_Expecter) TransformSimpleToClusterConfig(ctx interface{}, runtime interface{}, simpleConfig interface{}, filename interface{}) *MockK3dConfigProvider_TransformSimpleToClusterConfig_Call {
	return &MockK3dConfigProvider_TransformSimpleToClusterConfig_Call{Call: _e.mock.On("TransformSimpleToClusterConfig", ctx, runtime, simpleConfig, filename)}
}

func (_c *MockK3dConfigProvider_TransformSimpleToClusterConfig_Call) Run(run func(ctx context.Context, runtime runtimes.Runtime, simpleConfig v1alpha5.SimpleConfig, filename string)) *MockK3dConfigProvider_TransformSimpleToClusterConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 runtimes.Runtime
		if args[1] != nil {
			arg1 = args[1].(runtimes.Runtime)
		}
		var arg2 v1alpha5.SimpleConfig
		if args[2] != nil {
			arg2 = args[2].(v1alpha5.SimpleConfig)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockK3dConfigProvider_TransformSimpleToClusterConfig_Call) Return(clusterConfig *v1alpha5.ClusterConfig, err error) *MockK3dConfigProvider_TransformSimpleToClusterConfig_Call {
	_c.Call.Return(clusterConfig, err)
	return _c
}

func (_c *MockK3dConfigProvider_TransformSimpleToClusterConfig_Call) RunAndReturn(run func(ctx context.Context, runtime runtimes.Runtime, simpleConfig v1alpha5.SimpleConfig, filename string) (*v1alpha5.ClusterConfig, error)) *MockK3dConfigProvider_TransformSimpleToClusterConfig_Call {
	_c.Call.Return(run)
	return _c
}
