// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package quiet

import (
	"os"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFileOpener creates a new instance of MockFileOpener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileOpener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileOpener {
	mock := &MockFileOpener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileOpener is an autogenerated mock type for the FileOpener type
type MockFileOpener struct {
	mock.Mock
}

type MockFileOpener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileOpener) EXPECT() *MockFileOpener_Expecter {
	return &MockFileOpener_Expecter{mock: &_m.Mock}
}

// Open provides a mock function for the type MockFileOpener
func (_mock *MockFileOpener) Open(name string) (*os.File, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 *os.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*os.File, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *os.File); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileOpener_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockFileOpener_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - name string
func (_e *MockFileOpener_Expecter) Open(name interface{}) *MockFileOpener_Open_Call {
	return &MockFileOpener_Open_Call{Call: _e.mock.On("Open", name)}
}

func (_c *MockFileOpener_Open_Call) Run(run func(name string)) *MockFileOpener_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileOpener_Open_Call) Return(file *os.File, err error) *MockFileOpener_Open_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileOpener_Open_Call) RunAndReturn(run func(name string) (*os.File, error)) *MockFileOpener_Open_Call {
	_c.Call.Return(run)
	return _c
}
