name: Prepare KSail Binary
description: Restore or build the KSail binary from cache, handling path variations for different jobs.
author: Devantler Tech Platform Team

inputs:
  go-version:
    description: Go version from setup-go output, used to compute cache key.
    required: true
  source-hash:
    description: Hash of source files (from hashFiles() in workflow).
    required: true
  output-path:
    description: Target path for the binary relative to repository root (e.g., 'ksail' or 'bin/ksail'). Must not be an absolute path.
    required: false
    default: ksail
  run-smoke-test:
    description: Whether to run the smoke test after preparation.
    required: false
    default: 'true'

outputs:
  cache-hit:
    description: Whether the cache was hit ('true' or 'false').
    value: ${{ steps.ksail-cache.outputs.cache-hit }}
  binary-path:
    description: Absolute path to the prepared binary.
    value: ${{ steps.prepare.outputs.binary-path }}
  output-path-normalized:
    description: Normalized relative path to the binary (with leading './' stripped).
    value: ${{ steps.prepare.outputs.output-path-normalized }}

runs:
  using: composite
  steps:
    - name: 🔑 Compute ksail cache key
      id: ksail-cache-key
      shell: bash
      env:
        GO_VERSION: ${{ inputs.go-version }}
        SOURCE_HASH: ${{ inputs.source-hash }}
      run: |
        KSAIL_CACHE_KEY="${RUNNER_OS}-ksail-bin-${GO_VERSION}-${SOURCE_HASH}"
        printf 'value=%s\n' "$KSAIL_CACHE_KEY" >> "$GITHUB_OUTPUT"

    - name: ♻️ Restore cached ksail binary
      id: ksail-cache
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ./.cache/ksail
        key: ${{ steps.ksail-cache-key.outputs.value }}

    - name: 📦 Prepare ksail binary
      id: prepare
      shell: bash
      env:
        CACHE_HIT: ${{ steps.ksail-cache.outputs.cache-hit }}
        OUTPUT_PATH: ${{ inputs.output-path }}
      run: |
        set -Eeuo pipefail
        
        # Validate output path is relative and does not escape repository
        if [[ "$OUTPUT_PATH" = /* ]]; then
          echo "Error: output-path must be relative to repository root, got: $OUTPUT_PATH" >&2
          exit 1
        fi
        if [[ "$OUTPUT_PATH" == */../* ]]; then
          echo "Error: output-path must not contain '/../', got: $OUTPUT_PATH" >&2
          exit 1
        fi
        
        # Strip leading './' from OUTPUT_PATH for clearer path construction
        output_relative="${OUTPUT_PATH#./}"
        
        # Create output directory if needed
        output_dir=$(dirname "$output_relative")
        if [[ "$output_relative" == */* ]]; then mkdir -p "$output_dir"; fi
        
        if [ "$CACHE_HIT" = "true" ] && [ -f ./.cache/ksail ]; then
          # Use cached binary
          cp ./.cache/ksail "$output_relative"
        else
          # Build binary
          go build -C src -o "../${output_relative}" .
          # Store for cache
          mkdir -p ./.cache
          cp "$output_relative" ./.cache/ksail
        fi
        
        # Ensure binary is executable
        chmod +x "$output_relative"
        
        # Output absolute path and normalized relative path
        echo "binary-path=$(realpath "$output_relative")" >> "$GITHUB_OUTPUT"
        echo "output-path-normalized=$output_relative" >> "$GITHUB_OUTPUT"

    - name: ♻️ Save ksail binary cache
      if: steps.ksail-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ./.cache/ksail
        key: ${{ steps.ksail-cache-key.outputs.value }}

    - name: 🧪 Smoke test
      if: inputs.run-smoke-test == 'true'
      shell: bash
      env:
        OUTPUT_PATH_NORMALIZED: ${{ steps.prepare.outputs.output-path-normalized }}
      run: |
        set -Eeuo pipefail
        # Add ./ prefix for execution if path doesn't contain a directory separator
        if [[ "$OUTPUT_PATH_NORMALIZED" != */* ]]; then
          "./$OUTPUT_PATH_NORMALIZED" --version
        else
          "$OUTPUT_PATH_NORMALIZED" --version
        fi
