// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package installer

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockInstaller creates a new instance of MockInstaller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstaller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstaller {
	mock := &MockInstaller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInstaller is an autogenerated mock type for the Installer type
type MockInstaller struct {
	mock.Mock
}

type MockInstaller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstaller) EXPECT() *MockInstaller_Expecter {
	return &MockInstaller_Expecter{mock: &_m.Mock}
}

// Install provides a mock function for the type MockInstaller
func (_mock *MockInstaller) Install(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Install")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInstaller_Install_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Install'
type MockInstaller_Install_Call struct {
	*mock.Call
}

// Install is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInstaller_Expecter) Install(ctx interface{}) *MockInstaller_Install_Call {
	return &MockInstaller_Install_Call{Call: _e.mock.On("Install", ctx)}
}

func (_c *MockInstaller_Install_Call) Run(run func(ctx context.Context)) *MockInstaller_Install_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInstaller_Install_Call) Return(err error) *MockInstaller_Install_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInstaller_Install_Call) RunAndReturn(run func(ctx context.Context) error) *MockInstaller_Install_Call {
	_c.Call.Return(run)
	return _c
}

// Uninstall provides a mock function for the type MockInstaller
func (_mock *MockInstaller) Uninstall(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Uninstall")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInstaller_Uninstall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Uninstall'
type MockInstaller_Uninstall_Call struct {
	*mock.Call
}

// Uninstall is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInstaller_Expecter) Uninstall(ctx interface{}) *MockInstaller_Uninstall_Call {
	return &MockInstaller_Uninstall_Call{Call: _e.mock.On("Uninstall", ctx)}
}

func (_c *MockInstaller_Uninstall_Call) Run(run func(ctx context.Context)) *MockInstaller_Uninstall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInstaller_Uninstall_Call) Return(err error) *MockInstaller_Uninstall_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInstaller_Uninstall_Call) RunAndReturn(run func(ctx context.Context) error) *MockInstaller_Uninstall_Call {
	_c.Call.Return(run)
	return _c
}
