version: 2

before:
  hooks:
    - cmd: go mod tidy
      dir: .
    - cmd: go generate ./...
      dir: .

builds:
  - env:
      - CGO_ENABLED=0
    binary: ksail
    main: .
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - ../README.md
      - ../LICENSE*

dockers:
  - image_templates:
      - "ghcr.io/devantler-tech/ksail-go:{{ .Tag }}-amd64"
      - "ghcr.io/devantler-tech/ksail-go:latest-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
    goarch: amd64
  - image_templates:
      - "ghcr.io/devantler-tech/ksail-go:{{ .Tag }}-arm64"
      - "ghcr.io/devantler-tech/ksail-go:latest-arm64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/devantler-tech/ksail-go:{{ .Tag }}"
    image_templates:
      - "ghcr.io/devantler-tech/ksail-go:{{ .Tag }}-amd64"
      - "ghcr.io/devantler-tech/ksail-go:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/devantler-tech/ksail-go:latest"
    image_templates:
      - "ghcr.io/devantler-tech/ksail-go:latest-amd64"
      - "ghcr.io/devantler-tech/ksail-go:latest-arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^chore"
      - "^ci"
      - "^build"
      - "^style"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: "Breaking Changes"
      regexp: "^.*!:"
      order: 0
    - title: "Features"
      regexp: '^.*?feat(\(.+\))?!?:'
      order: 1
    - title: "Bug Fixes"
      regexp: '^.*?fix(\(.+\))?!?:'
      order: 2
    - title: "Performance Improvements"
      regexp: '^.*?perf(\(.+\))?!?:'
      order: 3
    - title: "Refactoring"
      regexp: '^.*?refactor(\(.+\))?!?:'
      order: 4
    - title: "Other Changes"
      order: 999

release:
  footer: |
    ## Quick Start

    **Homebrew** (macOS/Linux):
    ```bash
    brew install devantler-tech/taps/ksail
    ```

    **Go Install**:
    ```bash
    go install github.com/devantler-tech/ksail-go@{{ .Tag }}
    ```

    **Download Binary**: Choose your platform from the assets above

    **Docker**:
    ```bash
    docker pull ghcr.io/devantler-tech/ksail-go:{{ .Tag }}
    # or use :latest for the latest release
    ```

    ---
    **Full Changelog**: https://github.com/devantler-tech/ksail-go/compare/{{ .PreviousTag }}...{{ .Tag }}
