// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package helminstaller

import (
	"context"

	"github.com/mittwald/go-helm-client"
	mock "github.com/stretchr/testify/mock"
	"helm.sh/helm/v3/pkg/release"
)

// NewMockHelmClient creates a new instance of MockHelmClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHelmClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHelmClient {
	mock := &MockHelmClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHelmClient is an autogenerated mock type for the HelmClient type
type MockHelmClient struct {
	mock.Mock
}

type MockHelmClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHelmClient) EXPECT() *MockHelmClient_Expecter {
	return &MockHelmClient_Expecter{mock: &_m.Mock}
}

// InstallChart provides a mock function for the type MockHelmClient
func (_mock *MockHelmClient) InstallChart(ctx context.Context, spec *helmclient.ChartSpec, opts *helmclient.GenericHelmOptions) (*release.Release, error) {
	ret := _mock.Called(ctx, spec, opts)

	if len(ret) == 0 {
		panic("no return value specified for InstallChart")
	}

	var r0 *release.Release
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *helmclient.ChartSpec, *helmclient.GenericHelmOptions) (*release.Release, error)); ok {
		return returnFunc(ctx, spec, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *helmclient.ChartSpec, *helmclient.GenericHelmOptions) *release.Release); ok {
		r0 = returnFunc(ctx, spec, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*release.Release)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *helmclient.ChartSpec, *helmclient.GenericHelmOptions) error); ok {
		r1 = returnFunc(ctx, spec, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHelmClient_InstallChart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallChart'
type MockHelmClient_InstallChart_Call struct {
	*mock.Call
}

// InstallChart is a helper method to define mock.On call
//   - ctx context.Context
//   - spec *helmclient.ChartSpec
//   - opts *helmclient.GenericHelmOptions
func (_e *MockHelmClient_Expecter) InstallChart(ctx interface{}, spec interface{}, opts interface{}) *MockHelmClient_InstallChart_Call {
	return &MockHelmClient_InstallChart_Call{Call: _e.mock.On("InstallChart", ctx, spec, opts)}
}

func (_c *MockHelmClient_InstallChart_Call) Run(run func(ctx context.Context, spec *helmclient.ChartSpec, opts *helmclient.GenericHelmOptions)) *MockHelmClient_InstallChart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *helmclient.ChartSpec
		if args[1] != nil {
			arg1 = args[1].(*helmclient.ChartSpec)
		}
		var arg2 *helmclient.GenericHelmOptions
		if args[2] != nil {
			arg2 = args[2].(*helmclient.GenericHelmOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHelmClient_InstallChart_Call) Return(release1 *release.Release, err error) *MockHelmClient_InstallChart_Call {
	_c.Call.Return(release1, err)
	return _c
}

func (_c *MockHelmClient_InstallChart_Call) RunAndReturn(run func(ctx context.Context, spec *helmclient.ChartSpec, opts *helmclient.GenericHelmOptions) (*release.Release, error)) *MockHelmClient_InstallChart_Call {
	_c.Call.Return(run)
	return _c
}

// UninstallReleaseByName provides a mock function for the type MockHelmClient
func (_mock *MockHelmClient) UninstallReleaseByName(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for UninstallReleaseByName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHelmClient_UninstallReleaseByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UninstallReleaseByName'
type MockHelmClient_UninstallReleaseByName_Call struct {
	*mock.Call
}

// UninstallReleaseByName is a helper method to define mock.On call
//   - name string
func (_e *MockHelmClient_Expecter) UninstallReleaseByName(name interface{}) *MockHelmClient_UninstallReleaseByName_Call {
	return &MockHelmClient_UninstallReleaseByName_Call{Call: _e.mock.On("UninstallReleaseByName", name)}
}

func (_c *MockHelmClient_UninstallReleaseByName_Call) Run(run func(name string)) *MockHelmClient_UninstallReleaseByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHelmClient_UninstallReleaseByName_Call) Return(err error) *MockHelmClient_UninstallReleaseByName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHelmClient_UninstallReleaseByName_Call) RunAndReturn(run func(name string) error) *MockHelmClient_UninstallReleaseByName_Call {
	_c.Call.Return(run)
	return _c
}
