name: Setup Copilot Agent Environment

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: "Name for the environment setup"
        required: false
        default: "copilot-agent-dev"
  schedule:
    # Run weekly to keep environment fresh
    - cron: "0 0 * * 0"

env:
  # Environment variables for Copilot Agent
  COPILOT_AGENT_ENV: true
  GO_VERSION: "1.23.9"

jobs:
  setup-copilot-environment:
    name: Setup Environment for GitHub Copilot Agent
    runs-on: ubuntu-latest

    steps:
      - name: Checkout KSail repository for testing
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Setup Node.js for mega-linter-runner
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install mega-linter-runner
        run: |
          npm install -g mega-linter-runner

      - name: Verify installations
        run: |
          echo "=== Go Version ==="
          go version
          echo "=== Docker Version ==="
          docker --version
          echo "=== Node.js Version ==="
          node --version
          echo "=== npm Version ==="
          npm --version
          echo "=== mega-linter-runner Version ==="
          mega-linter-runner --help | head -5 || echo "mega-linter-runner help available"

      - name: Cache environment
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/.npm
          key: copilot-agent-env-${{ runner.os }}-go-${{ env.GO_VERSION }}-node-${{ hashFiles('**/package-lock.json', '**/go.sum') }}
          restore-keys: |
            copilot-agent-env-${{ runner.os }}-go-${{ env.GO_VERSION }}-

      - name: Test environment with KSail project
        run: |
          echo "=== Testing Go toolchain with KSail ==="
          go mod download
          go build -o ksail .
          ./ksail --version
          ./ksail --help

      - name: Test mega-linter-runner with KSail project
        run: |
          echo "=== Testing mega-linter-runner with KSail project ==="
          mega-linter-runner -f go --help | head -10
          echo "mega-linter-runner is ready for use with KSail Go project"

      - name: Environment setup complete
        run: |
          echo "🎉 GitHub Copilot Agent environment setup complete!"
          echo "✅ Go ${{ env.GO_VERSION }} installed"
          echo "✅ Docker installed and ready"
          echo "✅ mega-linter-runner installed and ready"
          echo "✅ Node.js and npm available for additional tools"
          echo ""
          echo "This environment is ready for GitHub Copilot Agent to work with KSail Go projects."
