name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: 'go.mod'
      - uses: pre-commit/action@2c7b3805e2f6a8003d7da6cd07e8e9d2a8f9c6f9 # v3.0.1
      - name: Commit changes
        if: failure()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git diff --cached --quiet || git commit -m "Apply pre-commit hook fixes"
          git push
